apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-hello-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: node-hello
  template:
    metadata:
      labels:
        app: node-hello
    spec:
      containers:
      - name: node-hello-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
 # --- INJECTING THE DATA ---
        env:
        - name: APP_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: node-hello-config
              key: APP_MESSAGE
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: node-hello-secret
              key: API_KEY